spring:
  datasource:
    url: jdbc:mysql://localhost:3306/helpad
    username: root
    password: ''
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
